services:
  client:
    build:
      context: .
    volumes:
      - ./app:/app/app
      - ./components:/app/components
    env_file:
      - .env

  server:
    build:
      context: ./server
    env_file:
      - .env
    develop:
      watch:
        - action: rebuild
          path: ./server

  nginx:
      image: nginx:latest
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80